- hosts: localhost
  tasks:
  - name: create a cloudformation stack
    amazon.aws.cloudformation:
      stack_name: "ansible-cloudformation-ec2-vpc"
      state: "present"
      region: "ap-south-1"
      disable_rollback: true
      template: "VPC_Single_Instance_In_Subnet.yml"
      template_parameters:
        KeyName: "ec2ansible"
        InstanceType: "t2.micro"
      tags:
        Stack: "ansible-cloudformation"
